### ISSUE TITLE
可否提供数据集？

### ISSUE THREAD

**Issue by alanrivers** [Lqlsoftware/UIMC#1]
你好，不知道你是否还有保留有 train_interaction 的数据吗？有的话可以分享一下吗？

**Comment by Lqlsoftware** [comment]
你好！
这是我本科时参加的比赛，数据集的话我这里已经没有保存了，需要数据的话可以尝试加比赛官方群询问下 `692148864`
当时的参赛链接 [https://www.kesci.com/home/competition/5ad306e633a98340e004f8d1](url)
以及比赛官网 [https://www.kuaishou.com/activity/uimc](url)
